FROM kong:3.4

USER root

# Install build dependencies
RUN apt-get update && apt-get install -y \
    git curl unzip gcc make luarocks lua5.1-dev \
 && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /tmp

# Clone plugin repo and install manually
RUN git clone https://github.com/jtbonhomme/kong-plugin-opa.git \
 && cd kong-plugin-opa \
 && luarocks make kong-opa-plugin-0.0.15-1.rockspec \
 && rm -rf kong-plugin-opa

USER kong
