services:
  frontend-dev:
    build:
      context: ./services/frontend-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./services/frontend-app/src:/app/src
      - ./services/frontend-app/public:/app/public
      - /app/node_modules
    networks:
      - on-prem-net
      - cloud-net
    depends_on:
      - keycloak
      - api-gateway
      - backend-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    image: kong:3.4
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./services/api-gateway/gateway-config.dev.yaml:/kong.yml:ro
    networks:
      - on-prem-net
      - cloud-net
    depends_on:
      - keycloak
      - backend-service
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  on-prem-net:
    external: true
  cloud-net:
    external: true 