FROM kong:latest

USER root
# Needed to extract LuaRocks manifests (avoids unzip-related errors)
RUN apt-get update && apt-get install -y git unzip curl wget gcc musl-dev lua5.1-dev luarocks

# Install the OPA plugin via LuaRocks
WORKDIR /tmp
RUN git clone https://github.com/wada-ama/kong-plugin-opa.git \
 && cd kong-plugin-opa \
 && luarocks make kong-plugin-opa-0.1.1-2.rockspec

USER kong
