_format_version: "2.1"

services:
  - name: backend-service
    url: http://backend-service:4000
    protocol: http
    host: backend-service
    port: 4000
    connect_timeout: 5000
    write_timeout: 5000
    read_timeout: 5000
    retries: 5

routes:
  - name: api-route
    service: backend-service
    protocols:
      - http
    paths:
      - /api
    strip_path: false
    preserve_host: true

  - name: admin-route
    service: backend-service
    protocols:
      - http
    paths:
      - /api/admin
    strip_path: false
    preserve_host: true

plugins:
  - name: jwt
    config:
      key_claim_name: kid
      secret_is_base64: false

  - name: external-authz
    config:
      url: http://opa:8181/v1/data/authz/allow
      method: POST
      body: '{"input": {"headers": {{headers}}, "method": "{{method}}", "path": "{{path}}"}}'
      timeout: 5000
      keepalive: 60000
      allow_on_error: false
      path_is_regex: false
      headers:
        - Authorization

  - name: prometheus
    config:
      status_codes: true
      bandwidth: true
      latency: true
      upstream_health: true
      http_requests: true
      http_status_codes: true
      latency_histogram_buckets:
        - 0.005
        - 0.01
        - 0.025
        - 0.05
        - 0.075
        - 0.1
        - 0.25
        - 0.5
        - 0.75
        - 1
        - 2.5
        - 5
        - 7.5
        - 10

  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      day: 10000
      policy: local
      fault_tolerant: true
      hide_client_headers: false 