global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@zerotrust-poc.com'
  smtp_auth_username: 'alerts@zerotrust-poc.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email-critical'
      continue: true
    - match:
        alertname: HighErrorRate
      receiver: 'email-critical'
      continue: true
    - match:
        alertname: AuthenticationFailure
      receiver: 'security-team'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

  - name: 'email-critical'
    email_configs:
      - to: 'admin@zerotrust-poc.com'
        headers:
          subject: 'Critical Alert: {{ .GroupLabels.alertname }}'
        send_resolved: true

  - name: 'security-team'
    email_configs:
      - to: 'security@zerotrust-poc.com'
        headers:
          subject: 'Security Alert: {{ .GroupLabels.alertname }}'
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SECURITY/WEBHOOK'
        channel: '#security-alerts'
        title: 'Security Alert: {{ .GroupLabels.alertname }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

templates:
  - '/etc/alertmanager/template/*.tmpl' 