global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'backend-service'
    static_configs:
      - targets: ['backend-service:4000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'opa'
    static_configs:
      - targets: ['opa:8181']
    metrics_path: /metrics
    scrape_interval: 10s
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093 