global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "express-gateway"
    static_configs:
      - targets: ["express-gateway:8000"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "opa"
    static_configs:
      - targets: ["opa:8181"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
