global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 25s
  external_labels:
    monitor: "zero-trust-poc"

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: "express-gateway"
    static_configs:
      - targets: ["express-gateway:8000"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 25s
    honor_labels: true

  - job_name: "opa"
    static_configs:
      - targets: ["opa:8181"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 25s
    honor_labels: true

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    scrape_timeout: 25s
    honor_labels: true

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      timeout: 30s
